### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by engeenity**

### CODE REVIEW

**Comment by AndreyAf** [comment]
you don't need "ng-controller="MapTubeCtrl as maptube" you have it in routes file - your ctrl is VM.

**Comment by AndreyAf** [comment]
please make changes and commit again

**Comment by engeenity** [comment]
Yeah I read about that here: http://www.johnpapa.net/angularjss-controller-as-and-the-vm-variable/
Still some stuff not so clear.

**Comment by AndreyAf** [comment]
the ctrl defined in state provider (routes file) there we also can see the 'ctrlAs' feature. If had any more questions feel free to ask

**Pull request closed without merging**
